### PR TITLE
Cache some reflection for performance and only apply color to wheel o…

### PR DESCRIPTION
**Pull request by Jawnnypoo**
…nce instead of for each visible edit text

### CODE REVIEW

**Comment by Rainer-Lang** [comment]
@StephenVinouze Possible to get this merged?

**Comment by StephenVinouze** [comment]
Hi @Rainer-Lang,

I no longer get the write access as I created this library on behalf of my previous organization. Unfortunately it seems it is no longer being maintained by them.

I will consider taking some time on my own to rewrite it with the several considerations from the PR that have been stacked up in this repo. Would be using Kotlin to simplify the code (no more builder pattern ^^)

If I do so, I will make sure to let you know ;)

**Comment by StephenVinouze** [comment]
In fact I believe I'll do it, lots of PRs waiting in the queue, that would be a shame to let it as is. Just need to find some time on my own, but porting it shouldn't take that long

**Comment by Rainer-Lang** [comment]
@StephenVinouze I really would appreciate if you will develop this or a fork of this very helpful lib.

**Comment by StephenVinouze** [comment]
Hey @Rainer-Lang,

So I rewrote the library using Kotlin (much more clearer that way). It's available [here](https://github.com/StephenVinouze/MaterialNumberPicker).
As of now it only replicates the features from this library. I invite you to try it and give me some feedback if anything went wrong while using it compared to this library.
I'll start implementing the fixes/PR in future versions, will let you know when this actual PR is being taken care of ;)

**Comment by Rainer-Lang** [comment]
@StephenVinouze Thanks. I'll switch to your lib. We could all discuss there. OK?

**Comment by StephenVinouze** [comment]
Yep indeed ;)

**Comment by StephenVinouze** [comment]
@Jawnnypoo I just looked into your work and I managed to lazy load (thanks Kotlin ^^) the fields and extracted the wheel customization from the for loop. Available on the `1.0.3` ;)

**Comment by Jawnnypoo** [comment]
Nice! Thanks!

**Pull request closed without merging**
